name: Challange_Plugin
main: de.wroracer.challange.Main
version: Snapshot-0.1
author: WRORacer

commands:
  nodead:
    description: Mit diesem Befehl änderst du due No Dead Challange
  timer:
    description: Mit diesem Befehl Steuerst du den Timer
  damage:
    description: Mit diesem Befehl Steuerst du die Damage Anouncment